language: java

jdk:
  - openjdk14


#sudo: false

env:
  global:
    - CODECOV_TOKEN="ca019ca5-1954-4725-a643-358c1ef15983"
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - glavstroi_e@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
  - postgresql

# Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres